name: Stylua Check

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  stylua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure Lua files are formatted
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
